export function createMatrixFixture() {
  const suite = {
    id: 'det.roles_quick_v1',
    label: 'Detection Roles Quick',
    tier: 'quick',
    family: 'detection',
    protocol: 'coco_detection',
    primaryMetric: 'ap_50_95',
    metricColumns: ['ap_50_95', 'avg_image_latency_ms'],
    requiredCapabilities: ['detection'],
    datasetRoot: '',
    manifestPath: '',
    sourceUrl: '',
    license: '',
    notes: '',
    datasetSplit: 'test',
    dvcRequired: true,
    requiresClip: false,
    fallbackDatasetRoots: [],
  };
  const assets = new Map([
    ['detector.soccana', {
      assetId: 'detector.soccana',
      kind: 'detector',
      provider: 'local',
      source: 'pretrained',
      label: 'soccana',
      version: 'pretrained',
      architecture: 'ultralytics_yolo',
      artifactPath: '/tmp/soccana.pt',
      bundleMode: 'separable',
      runtimeBinding: 'replace_component',
      available: true,
      capabilities: { detection: true, tracking: false, reid: false, calibration: false, team_id: false, role_id: true, jersey_ocr: false, event_spotting: false },
      classMapping: {},
      artifactDvc: null,
      availabilityError: null,
      trainingRunId: null,
      metrics: null,
      importOrigin: null,
      importedAt: null,
    }],
    ['detector.custom', {
      assetId: 'detector.custom',
      kind: 'detector',
      provider: 'huggingface',
      source: 'huggingface',
      label: 'custom',
      version: 'v1',
      architecture: 'rtdetr',
      artifactPath: '/tmp/custom.pt',
      bundleMode: 'separable',
      runtimeBinding: 'replace_component',
      available: true,
      capabilities: { detection: true, tracking: false, reid: false, calibration: false, team_id: false, role_id: true, jersey_ocr: false, event_spotting: false },
      classMapping: {},
      artifactDvc: null,
      availabilityError: null,
      trainingRunId: null,
      metrics: null,
      importOrigin: null,
      importedAt: null,
    }],
  ]);
  const recipes = [
    {
      id: 'detector:soccana',
      label: 'soccana',
      kind: 'detector_recipe',
      assetId: 'detector.soccana',
      sourceAssetIds: ['detector.soccana'],
      pipeline: 'classic',
      detectorAssetId: 'detector.soccana',
      trackerAssetId: null,
      requestedTrackerMode: null,
      keypointModel: null,
      bundleMode: 'separable',
      runtimeBinding: 'replace_component',
      available: true,
      artifactPath: '/tmp/soccana.pt',
      capabilities: { detection: true, tracking: false, reid: false, calibration: false, team_id: false, role_id: true, jersey_ocr: false, event_spotting: false },
      classMapping: {},
      compatibleSuiteIds: ['det.roles_quick_v1'],
    },
    {
      id: 'detector:custom',
      label: 'custom',
      kind: 'detector_recipe',
      assetId: 'detector.custom',
      sourceAssetIds: ['detector.custom'],
      pipeline: 'classic',
      detectorAssetId: 'detector.custom',
      trackerAssetId: null,
      requestedTrackerMode: null,
      keypointModel: null,
      bundleMode: 'separable',
      runtimeBinding: 'replace_component',
      available: true,
      artifactPath: '/tmp/custom.pt',
      capabilities: { detection: true, tracking: false, reid: false, calibration: false, team_id: false, role_id: true, jersey_ocr: false, event_spotting: false },
      classMapping: {},
      compatibleSuiteIds: ['det.roles_quick_v1'],
    },
    {
      id: 'pipeline:soccermaster',
      label: 'SoccerMaster',
      kind: 'pipeline_recipe',
      assetId: 'pipeline.soccermaster',
      sourceAssetIds: ['detector.soccana'],
      pipeline: 'soccermaster',
      detectorAssetId: null,
      trackerAssetId: null,
      requestedTrackerMode: null,
      keypointModel: null,
      bundleMode: 'bundled',
      runtimeBinding: 'full_pipeline',
      available: true,
      artifactPath: '/tmp/soccermaster',
      capabilities: { detection: true, tracking: true, reid: false, calibration: true, team_id: true, role_id: false, jersey_ocr: false, event_spotting: false },
      classMapping: {},
      compatibleSuiteIds: [],
    },
  ];
  const detail = {
    benchmarkId: 'b1',
    schemaVersion: 2,
    legacyRecord: false,
    label: 'matrix',
    status: 'completed',
    createdAt: '2026-03-12T00:00:00Z',
    primarySuiteId: 'det.roles_quick_v1',
    suiteIds: ['det.roles_quick_v1'],
    recipeIds: recipes.map((recipe) => recipe.id),
    assets: [],
    recipes,
    suiteResults: {
      'det.roles_quick_v1': {
        'detector:soccana': {
          suiteId: 'det.roles_quick_v1',
          recipeId: 'detector:soccana',
          status: 'completed',
          error: null,
          metrics: {
            ap_50_95: { label: 'AP@[.50:.95]', value: 0.81, displayValue: '0.8100', unit: '', sortValue: 0.81, isNa: false, raw: null },
            avg_image_latency_ms: { label: 'Latency', value: 18.2, displayValue: '18.20', unit: 'ms', sortValue: 18.2, isNa: false, raw: null },
          },
          flattenedMetrics: {},
          primaryMetric: 'ap_50_95',
          artifacts: {},
          rawResult: {},
          legacyRecord: false,
        },
        'detector:custom': {
          suiteId: 'det.roles_quick_v1',
          recipeId: 'detector:custom',
          status: 'completed',
          error: null,
          metrics: {
            ap_50_95: { label: 'AP@[.50:.95]', value: 0.67, displayValue: '0.6700', unit: '', sortValue: 0.67, isNa: false, raw: null },
            avg_image_latency_ms: { label: 'Latency', value: 9.7, displayValue: '9.70', unit: 'ms', sortValue: 9.7, isNa: false, raw: null },
          },
          flattenedMetrics: {},
          primaryMetric: 'ap_50_95',
          artifacts: {},
          rawResult: {},
          legacyRecord: false,
        },
      },
    },
    progress: 100,
    logs: [],
    error: null,
    dvcRuntime: null,
    legacyClipStatus: null,
  };
  const previewCells = {
    'det.roles_quick_v1::detector:soccana': { status: 'ready', reason: 'Runnable now' },
    'det.roles_quick_v1::detector:custom': { status: 'ready', reason: 'Runnable now' },
    'det.roles_quick_v1::pipeline:soccermaster': { status: 'not_supported', reason: 'Recipe does not satisfy this suite capability contract.' },
  };
  return { suite, assets, recipes, detail, previewCells };
}
